### ISSUE TITLE
Liquid syntax error: Unknown tag 'mermaid'

### ISSUE THREAD

**Issue by ManuelSchneid3r** [jasonbellamy/jekyll-mermaid#12]
https://travis-ci.org/github/albertlauncher/documentation
I build a page containing mermaid code using jekyll on travis. Afaik I set everything up as defined in the docs. However it is failing.  What am I doing wrong?

Error:
```
  Liquid Exception: Liquid syntax error (line 28): Unknown tag 'mermaid' in /home/travis/build/albertlauncher/documentation/src/_docs/extensions/python.md
                    ------------------------------------------------
      Jekyll 4.1.0   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
The command "jekyll build -s src -d ./site  && htmlproofer ./site" exited with 1.
```
Travis config
```yml
os: linux
dist: xenial
language: ruby

install: gem install jekyll html-proofer jekyll-mermaid

addons:
  apt:
    packages:
      - libcurl4-openssl-dev  # Avoid ssl errors

script: jekyll build -s src -d ./site  && htmlproofer ./site

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: ./deploy.sh
```

jekyll config
```yml
title: Albert
email: manuelschneid3r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://albertlauncher.github.io
github_username:  manuelschneid3r
repository: https://github.com/albertlauncher/albert.git
exclude: [vendor]

collections:
  docs:
    output: true

gems:
- jekyll-mermaid
```
